export default {
    "ADD":   { "opcode": 1,  "format": "R", "mode": 0 },
    "ADC":   { "opcode": 1,  "format": "R", "mode": 1 },
    "SUB":   { "opcode": 1,  "format": "R", "mode": 2 },
    "SBB":   { "opcode": 1,  "format": "R", "mode": 3 },
    "AND":   { "opcode": 4,  "format": "R" },
    "OR":    { "opcode": 5,  "format": "R" },
    "XOR":   { "opcode": 6,  "format": "R" },
    "NOT":   { "opcode": 7,  "format": "R" },
    "SHL":   { "opcode": 8,  "format": "R" },
    "SHR":   { "opcode": 9,  "format": "R" },
    "ADDI":  { "opcode": 2,  "format": "I" },
    "SUBI":  { "opcode": 3,  "format": "I" },
    "MOV":   { "opcode": 10, "format": "R" },
    "MVIH":  { "opcode": 11, "format": "S" },
    "MVIL":  { "opcode": 12, "format": "S" },
    "LDIDR": { "opcode": 16, "format": "I" },
    "STIDR": { "opcode": 17, "format": "I" },
    "LDIDX": { "opcode": 18, "format": "R" },
    "STIDX": { "opcode": 19, "format": "R" },
    "JMP":   { "opcode": 20, "format": "J" },
    "JMPI":  { "opcode": 21, "format": "I" },
    "JGEO":  { "opcode": 22, "format": "I" },
    "JLEO":  { "opcode": 23, "format": "I" },
    "JCO":   { "opcode": 24, "format": "J" },
    "JEO":   { "opcode": 25, "format": "I" },
    "PUSH":  { "opcode": 26, "format": "R" },
    "POP":   { "opcode": 27, "format": "R" },
    "CALL":  { "opcode": 13, "format": "R" },
    "JAL":   { "opcode": 14, "format": "J" },
    "MOVSP": { "opcode": 15, "format": "R" },
    "RET":   { "opcode": 28, "format": "R" },
    "STC":   { "opcode": 29, "format": "R" },
    "NOP":   { "opcode": 31, "format": "R" },
    "HLT":   { "opcode": 0,  "format": "R" },
    "RST":   { "opcode": 30, "format": "R" },
    "IE":    { "opcode": 1,  "format": "R" },
    "ID":    { "opcode": 1,  "format": "R" }
}
